#!/usr/bin/env python3
"""
HG002 SSB Damage Analysis
=========================

Analyse biotin-labelled single-strand break (SSB) sites detected by
nanopore sequencing of the HG002 diploid human genome.  Two figures are
produced from per-read XLSX tables generated by ``biotin_ssb_pipeline.py``:

  1_genome_wide_SSB_density
      Side-by-side maternal/paternal karyogram coloured by SSB density
      per 1 Mb bin.

  2_gene_annotation_SSB_analysis
      Sequencing coverage and SSB density stratified by genomic feature
      (Promoter, 5'UTR, CDS, 3'UTR, Intron, Exon-ncRNA, Intergenic).

Coordinate conventions
----------------------
- XLSX read tables are 1-based inclusive ``[start, end]``.
- Reverse-strand coordinates are flipped to forward-strand coordinates
  via ``chrom_length + 1 - pos``.
- GFF annotations are converted internally to 0-based half-open
  ``[start, end)``.  When classifying 1-based SSB positions against
  these intervals the positions are shifted by ``-1``.
- mtDNA (chrM) is excluded throughout.

Usage
-----
::

    python hg002_analysis.py                 # both figures
    python hg002_analysis.py density         # genome-wide density only
    python hg002_analysis.py annotation      # gene annotation only

Dependencies: numpy, pandas, matplotlib, pysam, openpyxl
"""

from __future__ import annotations

import gzip
import math
import os
import sys
from collections import defaultdict

import matplotlib
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch


# ====================================================================
# Input files — edit these paths to match your directory layout
# ====================================================================

# Per-read XLSX tables produced by biotin_ssb_pipeline.py
# Each file contains columns: contig, start, end, is_biotin, ...
XLSX_0KGY_FORWARD = "0kGy/0kGy_forward_all/0kGy_forward_all.xlsx"
XLSX_0KGY_REVERSE = "0kGy/0kGy_reverse_all/0kGy_reverse_all.xlsx"
XLSX_1KGY_FORWARD = "1kGy/1kGy_forward_all/1kGy_forward_all.xlsx"
XLSX_1KGY_REVERSE = "1kGy/1kGy_reverse_all/1kGy_reverse_all.xlsx"

# Reference genome FASTA (indexed; used to obtain chromosome lengths)
REFERENCE_FASTA = "reference/HG002_reference_forward.fasta"

# GFF gene annotations (gzipped, one per haplotype)
GFF_MATERNAL = "annotation/hg002.v1.1.loff.v0.6.mat.gff.gz"
GFF_PATERNAL = "annotation/hg002.v1.1.loff.v0.6.pat.gff.gz"

# Cytoband BED file (for p-arm / q-arm classification)
CYTOBAND_BED = "annotation/v1.1.cytoband.lifted.bed"

# Output directory
OUTPUT_DIR = "figures"

# ====================================================================
# Derived paths (do not edit)
# ====================================================================

XLSX_PATHS = {
    "0kGy_forward": XLSX_0KGY_FORWARD,
    "0kGy_reverse": XLSX_0KGY_REVERSE,
    "1kGy_forward": XLSX_1KGY_FORWARD,
    "1kGy_reverse": XLSX_1KGY_REVERSE,
}

GFF_FILES = {"mat": GFF_MATERNAL, "pat": GFF_PATERNAL}

# Chromosome ordering
AUTOSOMES = [f"chr{i}" for i in range(1, 23)]
CHROM_ORDER_NO_M = AUTOSOMES + ["chrX", "chrY"]

BIN_SIZE = 1_000_000   # 1 Mb windows for the density karyogram
PROMOTER_SIZE = 2_000   # bp upstream of TSS

# Genomic feature list — later entries take priority when regions overlap.
FEATURES = [
    "Intergenic", "Intron", "Exon (ncRNA)",
    "CDS", "3'UTR", "5'UTR", "Promoter",
]

FEATURE_COLORS = {
    "Intergenic":   "#D9D9D9",
    "Intron":       "#A6CEE3",
    "Exon (ncRNA)": "#4DAF4A",
    "CDS":          "#377EB8",
    "3'UTR":        "#FFD700",
    "5'UTR":        "#FF7F00",
    "Promoter":     "#E41A1C",
}


# ====================================================================
# Reference genome helpers
# ====================================================================

def get_chrom_lengths() -> dict[str, int]:
    """Return ``{contig_name: length}`` from the reference FASTA index."""
    import pysam
    with pysam.FastaFile(REFERENCE_FASTA) as fa:
        return {name: fa.get_reference_length(name)
                for name in fa.references}


def get_hap_chrom_sizes(bin_size: int = BIN_SIZE) -> dict[tuple, int]:
    """Return ``{(chrom, hap): size}`` rounded up to *bin_size*."""
    sizes = {}
    for contig, length in get_chrom_lengths().items():
        parts = contig.rsplit("_", 1)
        if len(parts) == 2:
            sizes[(parts[0], parts[1])] = math.ceil(length / bin_size) * bin_size
    return sizes


# ====================================================================
# I/O helpers
# ====================================================================

def load_xlsx(path: str) -> pd.DataFrame:
    """Load a per-read XLSX file."""
    return pd.read_excel(path)


def setup_plot_style() -> None:
    """Apply publication-quality matplotlib defaults."""
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": [
            "Liberation Sans", "Arial", "Helvetica", "DejaVu Sans"],
        "font.size": 10,
        "axes.titlesize": 12, "axes.labelsize": 11,
        "xtick.labelsize": 9, "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "figure.dpi": 150,
        "savefig.dpi": 300, "savefig.bbox": "tight",
        "savefig.pad_inches": 0.1,
        "axes.spines.top": False, "axes.spines.right": False,
    })


def save_figure(fig, name: str) -> None:
    """Save *fig* as PDF and PNG in ``OUTPUT_DIR``."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    for ext in ("pdf", "png"):
        path = os.path.join(OUTPUT_DIR, f"{name}.{ext}")
        fig.savefig(path)
        print(f"  Saved: {path}")
    plt.close(fig)


# ====================================================================
# Interval arithmetic
# ====================================================================

def merge_intervals(ivs: list[tuple]) -> np.ndarray:
    """Merge overlapping ``(start, end)`` pairs into an Nx2 int64 array."""
    if not ivs:
        return np.empty((0, 2), dtype=np.int64)
    s = sorted(ivs)
    merged = [list(s[0])]
    for a, b in s[1:]:
        if a <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], b)
        else:
            merged.append([a, b])
    return np.array(merged, dtype=np.int64)


def intervals_bases(ivs: np.ndarray) -> int:
    """Total base-pairs covered by merged intervals."""
    return 0 if len(ivs) == 0 else int(np.sum(ivs[:, 1] - ivs[:, 0]))


def pos_in_intervals(positions: np.ndarray, ivs: np.ndarray) -> np.ndarray:
    """Boolean mask indicating which *positions* fall inside *ivs*."""
    if len(ivs) == 0 or len(positions) == 0:
        return np.zeros(len(positions), dtype=bool)
    idx = np.searchsorted(ivs[:, 0], positions, side="right") - 1
    mask = np.zeros(len(positions), dtype=bool)
    ok = idx >= 0
    mask[ok] = positions[ok] < ivs[idx[ok], 1]
    return mask


# ====================================================================
# GFF annotation parsing
# ====================================================================

def _gff_contig(name: str) -> str:
    """Convert GFF contig names: ``chr1_MATERNAL`` -> ``chr1_mat``."""
    return name.replace("_MATERNAL", "_mat").replace("_PATERNAL", "_pat")


def _gff_attr(attrs: str, key: str) -> str | None:
    """Extract a single attribute value from a GFF attribute string."""
    for a in attrs.split(";"):
        if a.startswith(key + "="):
            return a.split("=", 1)[1]
    return None


def parse_gff(gff_path: str) -> dict[str, dict[str, np.ndarray]]:
    """Parse a GFF file into per-contig, per-feature merged interval arrays.

    Returns ``{contig: {feature_name: Nx2 int64 array}}`` in 0-based
    half-open coordinates.
    """
    gene_info: dict = {}
    gene_tx: dict[str, list] = defaultdict(list)
    tx_exons: dict[str, list] = defaultdict(list)
    tx_cds: dict[str, list] = defaultdict(list)

    print(f"  Parsing {os.path.basename(gff_path)} ...")
    with gzip.open(gff_path, "rt") as fh:
        for line in fh:
            if line[0] == "#":
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 9:
                continue
            contig, ft = _gff_contig(cols[0]), cols[2]
            s, e = int(cols[3]) - 1, int(cols[4])  # 1-based -> 0-based
            strand, at = cols[6], cols[8]

            if ft == "gene":
                gid = _gff_attr(at, "ID")
                gene_info[gid] = (contig, s, e, strand,
                                  _gff_attr(at, "gene_biotype"))
            elif ft == "transcript":
                gene_tx[_gff_attr(at, "Parent")].append(
                    _gff_attr(at, "ID"))
            elif ft == "exon":
                tx_exons[_gff_attr(at, "Parent")].append((s, e))
            elif ft == "CDS":
                tx_cds[_gff_attr(at, "Parent")].append((s, e))

    # Assign genomic regions to feature types
    raw: dict = defaultdict(lambda: defaultdict(list))
    for gid, (contig, gs, ge, strand, bio) in gene_info.items():
        coding = bio == "protein_coding"

        # Promoter (upstream of TSS)
        if strand == "+":
            ps, pe = max(0, gs - PROMOTER_SIZE), gs
        else:
            ps, pe = ge, ge + PROMOTER_SIZE
        if pe > ps:
            raw[contig]["Promoter"].append((ps, pe))

        # Gene body initially labelled as Intron; exon-level features
        # will take priority via the classify() priority list.
        raw[contig]["Intron"].append((gs, ge))

        for tid in gene_tx.get(gid, []):
            exons = tx_exons.get(tid, [])
            cdss = tx_cds.get(tid, [])
            if coding and cdss:
                cds_lo = min(c[0] for c in cdss)
                cds_hi = max(c[1] for c in cdss)
                for es, ee in exons:
                    for cs, ce in cdss:
                        ov_s, ov_e = max(cs, es), min(ce, ee)
                        if ov_s < ov_e:
                            raw[contig]["CDS"].append((ov_s, ov_e))
                    if strand == "+":
                        if es < cds_lo:
                            raw[contig]["5'UTR"].append(
                                (es, min(ee, cds_lo)))
                        if ee > cds_hi:
                            raw[contig]["3'UTR"].append(
                                (max(es, cds_hi), ee))
                    else:
                        if ee > cds_hi:
                            raw[contig]["5'UTR"].append(
                                (max(es, cds_hi), ee))
                        if es < cds_lo:
                            raw[contig]["3'UTR"].append(
                                (es, min(ee, cds_lo)))
            else:
                for es, ee in exons:
                    raw[contig]["Exon (ncRNA)"].append((es, ee))

    return {contig: {ft: merge_intervals(raw[contig][ft])
                     for ft in raw[contig]}
            for contig in raw}


# ====================================================================
# Feature classification
# ====================================================================

def classify(positions: np.ndarray,
             feat_contig: dict[str, np.ndarray]) -> np.ndarray:
    """Assign each 0-based position its highest-priority feature label.

    Features later in ``FEATURES`` take priority over earlier ones.
    """
    labels = np.full(len(positions), "Intergenic", dtype="U15")
    for ft in FEATURES:
        if ft == "Intergenic":
            continue
        ivs = feat_contig.get(ft)
        if ivs is not None and len(ivs) > 0:
            labels[pos_in_intervals(positions, ivs)] = ft
    return labels


def build_resolved_segments(
    feat_contig: dict[str, np.ndarray], chrom_len: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Partition a chromosome into non-overlapping segments, each labelled
    with its highest-priority feature.

    Returns ``(seg_starts, seg_ends, seg_labels)`` — all length-N arrays.
    """
    boundaries = sorted({0, chrom_len} | {
        int(coord)
        for ft in FEATURES
        for iv in (feat_contig.get(ft, []),)
        if len(iv) > 0
        for pair in iv
        for coord in pair
    })
    midpoints = np.array(
        [(boundaries[i] + boundaries[i + 1]) // 2
         for i in range(len(boundaries) - 1)],
        dtype=np.int64)
    return (np.array(boundaries[:-1], dtype=np.int64),
            np.array(boundaries[1:], dtype=np.int64),
            classify(midpoints, feat_contig))


def read_feature_overlap(
    starts: np.ndarray, ends: np.ndarray,
    seg_starts: np.ndarray, seg_ends: np.ndarray, seg_labels: np.ndarray,
) -> dict[str, int]:
    """Sum base-pair overlap of reads with each feature type.

    *starts* and *ends* should be 0-based half-open.
    """
    feat_bp: dict[str, int] = {f: 0 for f in FEATURES}
    for i in range(len(starts)):
        rs, re = int(starts[i]), int(ends[i])
        idx = np.searchsorted(seg_ends, rs, side="right")
        while idx < len(seg_starts) and seg_starts[idx] < re:
            ov = min(re, int(seg_ends[idx])) - max(rs, int(seg_starts[idx]))
            if ov > 0:
                feat_bp[seg_labels[idx]] += ov
            idx += 1
    return feat_bp


# ====================================================================
# Cytoband (p/q arm) parsing
# ====================================================================

def parse_cytoband() -> dict[str, dict[str, np.ndarray]]:
    """Return ``{contig: {'p': Nx2, 'q': Nx2}}`` from the BED file."""
    raw: dict = defaultdict(lambda: {"p": [], "q": []})
    with open(CYTOBAND_BED) as fh:
        for line in fh:
            cols = line.strip().split("\t")
            contig = _gff_contig(cols[0])
            if "chrM" in contig:
                continue
            s, e, band = int(cols[1]), int(cols[2]), cols[3]
            if band.startswith("p"):
                raw[contig]["p"].append((s, e))
            elif band.startswith("q"):
                raw[contig]["q"].append((s, e))
    return {c: {"p": merge_intervals(raw[c]["p"]),
                "q": merge_intervals(raw[c]["q"])}
            for c in raw}


# ====================================================================
# (1) Genome-wide SSB density
# ====================================================================

def compute_binned_density(dose: str,
                           bin_size: int = BIN_SIZE) -> pd.DataFrame:
    """Compute per-bin SSB density from per-read XLSX data.

    For each read the full ``[start, end]`` span contributes to
    ``base_coverage`` of overlapping bins, while ``biotin_hits`` is
    incremented only in the bin containing the 3' end of biotin-positive
    reads.  ``damage_per_Mb = biotin_hits / base_coverage * 1e6``.
    """
    chrom_lengths = get_chrom_lengths()
    bins: dict[tuple, dict] = {}

    def accumulate(df: pd.DataFrame, reverse: bool) -> None:
        for contig, grp in df.groupby("contig"):
            if contig not in chrom_lengths:
                continue
            clen = chrom_lengths[contig]
            for _, row in grp.iterrows():
                s, e = int(row["start"]), int(row["end"])
                if reverse:
                    s, e = clen + 1 - e, clen + 1 - s
                # Coverage: count overlapping bases per bin
                for b in range((s // bin_size) * bin_size,
                               (e // bin_size) * bin_size + bin_size,
                               bin_size):
                    rec = bins.setdefault((contig, b),
                                         {"base_coverage": 0,
                                          "biotin_hits": 0})
                    rec["base_coverage"] += (
                        min(e, b + bin_size - 1) - max(s, b) + 1)
                # SSB site: 3' end of biotin-positive reads
                if row["is_biotin"]:
                    end_bin = (e // bin_size) * bin_size
                    bins.setdefault((contig, end_bin),
                                   {"base_coverage": 0,
                                    "biotin_hits": 0})["biotin_hits"] += 1

    for strand, reverse in [("forward", False), ("reverse", True)]:
        key = f"{dose}_{strand}"
        print(f"  Loading {key} ...")
        df = load_xlsx(XLSX_PATHS[key])
        accumulate(df, reverse)
        print(f"    {len(df)} reads")

    rows = []
    for (contig, bin_start), rec in bins.items():
        chrom, *rest = contig.rsplit("_", 1)
        hap = rest[0] if rest else "unknown"
        bc, bh = rec["base_coverage"], rec["biotin_hits"]
        rows.append({
            "contig": contig, "chrom": chrom, "haplotype": hap,
            "bin_start": bin_start,
            "base_coverage": bc, "biotin_hits": bh,
            "damage_per_Mb": (bh / bc * 1e6) if bc > 0 else 0,
        })
    return pd.DataFrame(rows)


def _density_track(data: pd.DataFrame, chrom: str, max_bins: int,
                   bin_size: int = BIN_SIZE,
                   haplotype: str | None = None) -> np.ndarray:
    """Extract a 1-D density array for one chromosome (and haplotype)."""
    mask = data["chrom"] == chrom
    if haplotype is not None:
        mask &= data["haplotype"] == haplotype
    arr = np.full(max_bins, np.nan)
    for _, row in data.loc[mask].iterrows():
        idx = int(row["bin_start"]) // bin_size
        if idx < max_bins:
            arr[idx] = row["damage_per_Mb"]
    return arr


def plot_karyogram(data_0kgy: pd.DataFrame,
                   data_1kgy: pd.DataFrame,
                   bin_size: int = BIN_SIZE) -> plt.Figure:
    """Draw a side-by-side maternal | paternal karyogram.

    Each chromosome row has two tracks (1 kGy top, 0 kGy bottom) per
    haplotype.  chrX appears under maternal, chrY under paternal.
    """
    setup_plot_style()
    hap_sizes = get_hap_chrom_sizes(bin_size)

    # Determine chromosome widths (max of mat/pat)
    chrom_sizes: dict[str, int] = {}
    for chrom in CHROM_ORDER_NO_M:
        for hap in ("mat", "pat"):
            if (chrom, hap) in hap_sizes:
                chrom_sizes[chrom] = max(chrom_sizes.get(chrom, 0),
                                         hap_sizes[(chrom, hap)])

    # Rows: autosomes + combined X/Y row
    auto = [c for c in CHROM_ORDER_NO_M if c not in ("chrX", "chrY")]
    rows = [c for c in auto if c in chrom_sizes]
    if "chrX" in chrom_sizes or "chrY" in chrom_sizes:
        rows.append("chrX/Y")
        chrom_sizes["chrX/Y"] = max(chrom_sizes.get("chrX", 0),
                                     chrom_sizes.get("chrY", 0))

    n_rows = len(rows)
    max_size = max(chrom_sizes.values())
    max_bins = max_size // bin_size
    gap = 0.3  # vertical gap between 1 kGy and 0 kGy tracks

    fig, axes = plt.subplots(
        n_rows, 2, figsize=(16, n_rows * 0.5 + 2),
        gridspec_kw={"hspace": 0.15, "wspace": 0.05})
    if n_rows == 1:
        axes = axes[np.newaxis, :]

    # Colour scale: 95th percentile of 1 kGy
    vals_1k = data_1kgy["damage_per_Mb"].dropna()
    vmax = (np.percentile(vals_1k[vals_1k > 0], 95)
            if len(vals_1k[vals_1k > 0]) > 0 else 10)
    norm = Normalize(vmin=0, vmax=vmax, clip=True)
    cmap = plt.cm.YlOrRd.copy()
    cmap.set_bad("white")

    for ri, row_label in enumerate(rows):
        for ci, hap in enumerate(("mat", "pat")):
            ax = axes[ri, ci]
            chrom = (("chrX" if hap == "mat" else "chrY")
                     if row_label == "chrX/Y" else row_label)

            t1 = _density_track(data_1kgy, chrom, max_bins, bin_size, hap)
            t0 = _density_track(data_0kgy, chrom, max_bins, bin_size, hap)

            if np.all(np.isnan(t1)):
                ax.set_visible(False)
                continue

            ref = hap_sizes.get((chrom, hap),
                                chrom_sizes.get(chrom, max_size))
            ax.imshow(t1[np.newaxis, :], aspect="auto", cmap=cmap,
                      norm=norm, extent=[0, max_size, 1 + gap, 2 + gap],
                      interpolation="nearest")
            ax.imshow(t0[np.newaxis, :], aspect="auto", cmap=cmap,
                      norm=norm, extent=[0, max_size, 0, 1],
                      interpolation="nearest")
            for y0 in (1 + gap, 0):
                ax.add_patch(mpatches.Rectangle(
                    (0, y0), ref, 1,
                    facecolor="none", edgecolor="black", linewidth=0.5))
            ax.set(xlim=(0, max_size), ylim=(-0.1, 2 + gap + 0.1))
            ax.set_yticks([])
            ax.set_xticks([])
            for sp in ax.spines.values():
                sp.set_visible(False)

        # Chromosome label
        ymid = (2 + gap) / 2
        if row_label == "chrX/Y":
            axes[ri, 0].text(-max_size * 0.02, ymid, "X", ha="right",
                             va="center", fontsize=9, fontweight="bold")
            axes[ri, 1].text(max_size * 1.02, ymid, "Y", ha="left",
                             va="center", fontsize=9, fontweight="bold")
        else:
            axes[ri, 0].text(-max_size * 0.02, ymid,
                             row_label.replace("chr", ""), ha="right",
                             va="center", fontsize=9, fontweight="bold")

    axes[0, 0].set_title("maternal", fontsize=11, fontweight="bold", pad=8)
    axes[0, 1].set_title("paternal", fontsize=11, fontweight="bold", pad=8)

    # Scale bar
    sb = 50_000_000
    axes[-1, 0].plot([0, sb], [-0.5, -0.5], "k-", lw=1.5, clip_on=False)
    axes[-1, 0].text(sb / 2, -0.8, "50 Mb", ha="center", va="top",
                     fontsize=8, clip_on=False)

    # Colour bar
    sm = ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cb_ax = fig.add_axes([0.92, 0.3, 0.012, 0.4])
    cb = fig.colorbar(sm, cax=cb_ax)
    cb.set_label("SSB density\n(per Mb)", fontsize=9)
    cb.ax.tick_params(labelsize=8)

    fig.suptitle("Genome-wide SSB Damage Distribution",
                 fontsize=14, fontweight="bold", y=0.98)
    return fig


def generate_genome_wide_density() -> None:
    """End-to-end: compute binned density and save karyogram."""
    print("=== Genome-wide SSB density ===")
    bins_0 = compute_binned_density("0kGy")
    bins_1 = compute_binned_density("1kGy")

    combined = pd.concat([bins_0.assign(dose="0kGy"),
                          bins_1.assign(dose="1kGy")], ignore_index=True)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    for ext, method in [("csv", "to_csv"), ("xlsx", "to_excel")]:
        getattr(combined, method)(
            os.path.join(OUTPUT_DIR,
                         f"1_genome_wide_SSB_density_data.{ext}"),
            index=False)

    fig = plot_karyogram(bins_0, bins_1)
    save_figure(fig, "1_genome_wide_SSB_density")
    print("Done.\n")


# ====================================================================
# (2) Gene annotation SSB analysis
# ====================================================================

def process_dose(
    dose: str,
    feat: dict[str, dict],
    chrom_lengths: dict[str, int],
    segments: dict[str, tuple],
) -> tuple[dict, dict, dict]:
    """Classify reads and SSB sites by genomic feature for one dose.

    Returns ``(feat_bp, feat_biotin, ssb_positions)`` where:

    - *feat_bp*: total sequenced base-pairs per feature (denominator).
    - *feat_biotin*: biotin-positive read count per feature (numerator).
    - *ssb_positions*: ``{contig: sorted int64 array}`` of SSB 3' ends.
    """
    feat_bp: dict[str, int] = {f: 0 for f in FEATURES}
    feat_biotin: dict[str, int] = {f: 0 for f in FEATURES}
    ssb_pos: dict[str, list] = defaultdict(list)

    for strand in ("forward", "reverse"):
        key = f"{dose}_{strand}"
        print(f"  Loading {key} ...")
        df = pd.read_excel(XLSX_PATHS[key])
        df = df[~df["contig"].str.contains("chrM")]

        for contig, grp in df.groupby("contig"):
            if contig not in segments:
                continue
            seg_s, seg_e, seg_l = segments[contig]
            clen = chrom_lengths[contig]

            starts = grp["start"].values.astype(np.int64)
            ends = grp["end"].values.astype(np.int64)
            is_bio = grp["is_biotin"].values.astype(bool)

            if strand == "reverse":
                starts, ends = clen + 1 - ends, clen + 1 - starts
                bio_ends = starts[is_bio]      # 3' end = new start
            else:
                bio_ends = ends[is_bio]         # 3' end = end

            # Denominator: read-feature overlap
            # 1-based [start,end] -> 0-based [start-1, end)
            bp = read_feature_overlap(starts - 1, ends, seg_s, seg_e, seg_l)
            for f in FEATURES:
                feat_bp[f] += bp[f]

            # Numerator: classify biotin 3' ends (1-based -> 0-based)
            if len(bio_ends) > 0:
                bio_sorted = np.sort(bio_ends)
                labels = classify(bio_sorted - 1, feat[contig])
                for f in FEATURES:
                    feat_biotin[f] += int(np.sum(labels == f))
                ssb_pos[contig].append(bio_sorted)

            print(f"    {contig}: {len(grp)} reads")

    merged = {c: np.sort(np.concatenate(arrs))
              for c, arrs in ssb_pos.items()}
    return feat_bp, feat_biotin, merged


def plot_annotation(genome_size: dict[str, int],
                    results: dict) -> plt.Figure:
    """Draw two-panel figure: coverage and SSB density by genomic feature.

    Panel A — horizontal bars showing sequencing coverage (x) per feature.
    Panel B — horizontal bars showing SSB density (SSB per Mb) per feature.
    """
    setup_plot_style()

    fig = plt.figure(figsize=(10, 4))
    gs = GridSpec(1, 2, width_ratios=[1, 1.2], wspace=0.4,
                  left=0.10, right=0.95, bottom=0.18, top=0.86)
    width = 0.35

    # Sort features by 1 kGy SSB density (descending)
    dens_1 = {f: results["1kGy"]["density"][f] * 1e6 for f in FEATURES}
    order = sorted(FEATURES, key=lambda f: dens_1[f], reverse=True)
    y = np.arange(len(order))

    # -- Panel A: Sequencing coverage --
    ax_a = fig.add_subplot(gs[0])
    cov = {}
    for dose in ("0kGy", "1kGy"):
        cov[dose] = [results[dose]["bp"][f] / genome_size[f]
                     if genome_size[f] > 0 else 0 for f in order]
    mb = {dose: [results[dose]["bp"][f] / 1e6 for f in order]
          for dose in ("0kGy", "1kGy")}
    colors = [FEATURE_COLORS[f] for f in order]

    ax_a.barh(y - width / 2, cov["1kGy"], height=width,
              color=colors, edgecolor="black", linewidth=0.5, alpha=0.9)
    ax_a.barh(y + width / 2, cov["0kGy"], height=width,
              color=colors, edgecolor="black", linewidth=0.5, alpha=0.5)
    ax_a.set_yticks(y)
    ax_a.set_yticklabels(order, fontsize=10)
    ax_a.set_xlabel("Sequencing coverage (x)", fontsize=10)
    ax_a.set_title("A. Coverage by genomic feature",
                    fontweight="bold", loc="left", fontsize=11)
    ax_a.invert_yaxis()

    mb_x = min(min(cov["1kGy"]), min(cov["0kGy"])) * 0.5
    for i in range(len(order)):
        for dose, dy, alpha in [("1kGy", -width / 2, 0.9),
                                ("0kGy", +width / 2, 0.5)]:
            ax_a.text(cov[dose][i] * 1.02, i + dy,
                      f"{cov[dose][i]:.2f}x",
                      va="center", ha="left", fontsize=8)
            ax_a.text(mb_x, i + dy, f"{mb[dose][i]:.0f} Mb",
                      va="center", ha="center", fontsize=7,
                      fontweight="bold")
    ax_a.set_xlim(0, max(cov["1kGy"]) * 1.25)

    # -- Panel B: SSB density --
    ax_b = fig.add_subplot(gs[1])
    dens = {dose: [results[dose]["density"][f] * 1e6 for f in order]
            for dose in ("0kGy", "1kGy")}

    ax_b.barh(y - width / 2, dens["1kGy"], height=width,
              color=colors, edgecolor="black", linewidth=0.5, alpha=0.9)
    ax_b.barh(y + width / 2, dens["0kGy"], height=width,
              color=colors, edgecolor="black", linewidth=0.5, alpha=0.5)
    ax_b.set_yticks(y)
    ax_b.set_yticklabels(order, fontsize=10)
    ax_b.set_xlabel("SSB density (SSB per Mb)", fontsize=10)
    ax_b.set_title("B. SSB density by feature",
                    fontweight="bold", loc="left", fontsize=11)
    ax_b.invert_yaxis()
    ax_b.legend(handles=[
        Patch(facecolor="gray", edgecolor="black", alpha=0.9, label="1 kGy"),
        Patch(facecolor="gray", edgecolor="black", alpha=0.5, label="0 kGy"),
    ], fontsize=9, frameon=False)

    for i in range(len(order)):
        for dose, dy in [("1kGy", -width / 2), ("0kGy", +width / 2)]:
            ax_b.text(dens[dose][i] * 1.02, i + dy,
                      f"{dens[dose][i]:.1f}",
                      va="center", ha="left", fontsize=8)
    ax_b.set_xlim(0, max(dens["1kGy"]) * 1.25)

    fig.suptitle("SSB Damage Distribution by Genomic Feature",
                 fontsize=13, fontweight="bold")
    return fig


def generate_annotation_analysis() -> None:
    """End-to-end: parse annotations, quantify SSBs, and save figure."""
    print("=== Gene annotation SSB analysis ===")

    # Parse GFF annotations
    feat: dict = {}
    for path in GFF_FILES.values():
        feat.update(parse_gff(path))

    chrom_lengths = {k: v for k, v in get_chrom_lengths().items()
                     if "chrM" not in k}
    feat = {k: v for k, v in feat.items() if "chrM" not in k}

    # Build resolved segments
    print("\nBuilding resolved segments ...")
    segments = {}
    for contig, fdict in feat.items():
        clen = chrom_lengths.get(contig)
        if clen is not None:
            segments[contig] = build_resolved_segments(fdict, clen)

    # Genome feature sizes
    print("\nGenome feature sizes:")
    genome_size: dict[str, int] = {f: 0 for f in FEATURES}
    total = sum(chrom_lengths[c] for c in chrom_lengths if c in feat)
    for contig in feat:
        if contig not in segments:
            continue
        ss, se, sl = segments[contig]
        for i in range(len(ss)):
            genome_size[sl[i]] += int(se[i] - ss[i])
    for f in FEATURES:
        print(f"  {f:<16}: {genome_size[f]:>14,} bp "
              f"({genome_size[f] / total * 100:.2f}%)")

    # Process each dose
    results: dict = {}
    all_ssb: dict = {}
    for dose in ("0kGy", "1kGy"):
        print(f"\n=== {dose} ===")
        bp, bio, ssb = process_dose(dose, feat, chrom_lengths, segments)
        dens = {f: bio[f] / bp[f] if bp[f] > 0 else 0 for f in FEATURES}
        results[dose] = {"bp": bp, "biotin": bio, "density": dens}
        all_ssb[dose] = ssb

        print(f"\n  {'Feature':<16} | {'sequenced_bp':>14} | "
              f"{'biotin_reads':>12} | {'SSB/bp':>12}")
        print("  " + "-" * 58)
        for f in FEATURES:
            print(f"  {f:<16} | {bp[f]:>14,} | "
                  f"{bio[f]:>12,} | {dens[f]:>12.4e}")

    # p/q arm analysis (1 kGy)
    print("\n=== p-arm vs q-arm (1 kGy) ===")
    arms = parse_cytoband()
    arm_rows = []
    for contig in sorted(all_ssb["1kGy"]):
        positions = all_ssb["1kGy"][contig]
        if contig not in arms or len(positions) == 0:
            continue
        for arm in ("p", "q"):
            ivs = arms[contig][arm]
            if len(ivs) == 0:
                continue
            n = int(np.sum(pos_in_intervals(positions - 1, ivs)))
            size_mb = intervals_bases(ivs) / 1e6
            chrom, hap = contig.rsplit("_", 1)
            arm_rows.append({
                "contig": contig, "chrom": chrom, "haplotype": hap,
                "arm": arm, "ssb_count": n,
                "arm_size_mb": size_mb,
                "density": n / size_mb if size_mb > 0 else 0,
            })
    arm_df = pd.DataFrame(arm_rows)
    print(arm_df.groupby("arm")[["ssb_count", "density"]].mean())

    # Save data
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    base = "2_gene_annotation_SSB_analysis"

    coverage = {
        dose: {f: results[dose]["bp"][f] / genome_size[f]
               if genome_size[f] > 0 else 0 for f in FEATURES}
        for dose in ("0kGy", "1kGy")}
    feat_rows = []
    for f in FEATURES:
        row: dict = {"feature": f, "genome_size_bp": genome_size[f]}
        for dose in ("0kGy", "1kGy"):
            row[f"{dose}_sequenced_bp"] = results[dose]["bp"][f]
            row[f"{dose}_coverage"] = coverage[dose][f]
            row[f"{dose}_biotin_reads"] = results[dose]["biotin"][f]
            row[f"{dose}_SSB_per_bp"] = results[dose]["density"][f]
            row[f"{dose}_SSB_per_Mb"] = results[dose]["density"][f] * 1e6
        feat_rows.append(row)

    feat_df = pd.DataFrame(feat_rows)
    feat_df.to_csv(os.path.join(OUTPUT_DIR, f"{base}_data.csv"), index=False)
    feat_df.to_excel(os.path.join(OUTPUT_DIR, f"{base}_data.xlsx"),
                     index=False)
    arm_df.to_csv(os.path.join(OUTPUT_DIR, f"{base}_arms.csv"), index=False)
    arm_df.to_excel(os.path.join(OUTPUT_DIR, f"{base}_arms.xlsx"),
                    index=False)
    print("\n  Data saved.")

    fig = plot_annotation(genome_size, results)
    save_figure(fig, base)
    print("Done.\n")


# ====================================================================
# Entry point
# ====================================================================

if __name__ == "__main__":
    target = sys.argv[1].lower() if len(sys.argv) > 1 else "all"

    if target in ("all", "density"):
        generate_genome_wide_density()
    if target in ("all", "annotation"):
        generate_annotation_analysis()
    if target not in ("all", "density", "annotation"):
        print(f"Unknown: {target}")
        print("Usage: python hg002_analysis.py [density|annotation]")
        sys.exit(1)
